kind = "web"
previewPath = "/"
title = "Kittangi OS"
version = "1.0.0"
id = "artifacts/kittangi-os"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23182

[services.development]
run = "pnpm --filter @workspace/kittangi-os run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/kittangi-os", "run", "build" ]
publicDir = "artifacts/kittangi-os/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23182"
BASE_PATH = "/"
